trigger:
- main
- feature/*
- issue/*

variables:
  buildConfiguration: 'Release'

stages:
- stage: Excel
  jobs:
  - job: Windows
    timeoutInMinutes: 180

    pool:
      vmImage: 'windows-latest'

    strategy:
      matrix:
        Excel32:
          options: '--forcex86'
          target: 'ci'
        Excel64:
          options: ''
          target: 'ci'
      maxParallel: 4

    steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: 10.0.x
        includePreviewVersions: true
      displayName: 'Use .NET 10.0 sdk'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          choco install office365business $(options)
        failOnStderr: true
      displayName: 'Install Excel'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Import-PfxCertificate -FilePath $(Build.SourcesDirectory)/src/Allors.Excel.Interop.Vsto/ExcelAddIn.VSTO_TemporaryKey.pfx -CertStoreLocation Cert:\CurrentUser\My
        failOnStderr: true
      displayName: 'Add Excel PFX file to the certificate store.'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          choco install go-task -y
        failOnStderr: true
      displayName: 'Install go-task'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          task $(target) CONFIGURATION=$(buildConfiguration)
        failOnStderr: false
      displayName: 'Build'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'xunit'
        testResultsFiles: '*.xml'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/tests'
      displayName: 'Publish Test results'
    - task: NuGetAuthenticate@1
      displayName: 'NuGet Authenticate'
    - task: NuGetCommand@2
      displayName: 'NuGet push'
      inputs:
        command: push
        packagesToPush: '$(Build.SourcesDirectory)/**/*.nupkg;$(Build.SourcesDirectory)/**/*.snupkg;!$(Build.SourcesDirectory)/**/*.symbols.nupkg'
        publishVstsFeed: 'Excel/Excel'
        allowPackageConflicts: true

